# Build nativo deve ser feito localmente primeiro:
# mvn clean package -Pnative -DskipTests

# Runtime com GLIBC 2.34+ compatível
FROM registry.access.redhat.com/ubi9-minimal:latest
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work /work/application
EXPOSE 8080
ENV PORT=8080
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
